import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Arabic } from "next/font/google";
import "./globals.css";
import { QRCodeProvider } from "@/context/qrCodeContext";

const notoSansArabic = Noto_Sans_Arabic({
  subsets: ['arabic'], // Ensure the Arabic subset is loaded
  weight: ['100', '400', '700', '900'], // Add desired font weights
  display: 'swap', // Matches your desired CSS `font-display`
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSansArabic.className} antialiased bg-neutral-100`}
      >
        <QRCodeProvider>
          {children}
        </QRCodeProvider>
      </body>
    </html>
  );
}
